export enum Colors {
  Cyan = '#bae2ff',
  LightGreen = '#b9ffdd',
  Yellow = '#ffe8ac',
  LightRose = '#ffcab9',
  LightRed = '#f99494',
  Blue = '#9dd5ff',
  Rose = '#eca1ff',
  Green = '#daff8b',
  Orange = '#ffa285',
  Gray = '#cdcdcd',
  DarkGray = '#979797',
  Rust = '#a99a7c',
  Default = '#ffffff',
}
